# Generated by Django 5.2.8 on 2025-11-11 05:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blades",
                    models.IntegerField(
                        default=0,
                        help_text="Proficiency with swords and bladed weapons",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "axes",
                    models.IntegerField(
                        default=0,
                        help_text="Proficiency with axes and chopping weapons",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "maces",
                    models.IntegerField(
                        default=0,
                        help_text="Proficiency with maces and blunt weapons",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "spears",
                    models.IntegerField(
                        default=0,
                        help_text="Proficiency with spears and polearms",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "crossbows",
                    models.IntegerField(
                        default=0,
                        help_text="Proficiency with crossbows and ranged weapons",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "brawling",
                    models.IntegerField(
                        default=0,
                        help_text="Unarmed combat proficiency",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "alchemy",
                    models.IntegerField(
                        default=0,
                        help_text="Potion-making and alchemical knowledge (requires access)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "magery",
                    models.IntegerField(
                        default=0,
                        help_text="Spell-casting ability (requires access)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "sign_sorcery",
                    models.IntegerField(
                        default=0,
                        help_text="Witcher sign magic (requires access)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "crafting_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("smithing", "Smithing"),
                            ("carpentry", "Carpentry"),
                            ("herbalism", "Herbalism"),
                        ],
                        default="none",
                        help_text="Crafting specialization",
                        max_length=20,
                    ),
                ),
                (
                    "crafting_skill",
                    models.IntegerField(
                        default=0,
                        help_text="Crafting skill level",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "athletics",
                    models.IntegerField(
                        default=0,
                        help_text="Physical fitness, running, jumping, climbing",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Skills",
                "verbose_name_plural": "Character Skills",
            },
        ),
        migrations.CreateModel(
            name="CharacterStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strength",
                    models.IntegerField(
                        default=1,
                        help_text="Physical power and melee damage",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "agility",
                    models.IntegerField(
                        default=1,
                        help_text="Speed, reflexive dodging, and finesse",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "endurance",
                    models.IntegerField(
                        default=1,
                        help_text="Stamina, health, and resistance",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "reflexes",
                    models.IntegerField(
                        default=1,
                        help_text="Reaction speed and initiative",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "wit",
                    models.IntegerField(
                        default=1,
                        help_text="Quick thinking and cleverness",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "intelligence",
                    models.IntegerField(
                        default=1,
                        help_text="Knowledge and reasoning",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "willpower",
                    models.IntegerField(
                        default=1,
                        help_text="Mental fortitude and magic power",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "perception",
                    models.IntegerField(
                        default=1,
                        help_text="Awareness and noticing details",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "charm",
                    models.IntegerField(
                        default=1,
                        help_text="Charisma and likability",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "appearance",
                    models.IntegerField(
                        default=1,
                        help_text="Physical attractiveness",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "graces",
                    models.IntegerField(
                        default=1,
                        help_text="Social grace and etiquette",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "cunning",
                    models.IntegerField(
                        default=1,
                        help_text="Deception and manipulation",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Stats",
                "verbose_name_plural": "Character Stats",
            },
        ),
        migrations.CreateModel(
            name="Vocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("soldier", "Soldier"),
                            ("bladesman", "Bladesman"),
                            ("knight", "Knight"),
                            ("inquisitor", "Inquisitor"),
                            ("sorcerer", "Sorcerer/ess"),
                            ("witcher", "Witcher"),
                            ("courtesan", "Courtesan"),
                            ("infiltrator", "Infiltrator"),
                            ("noble", "Noble"),
                            ("alchemist", "Alchemist"),
                            ("merchant", "Merchant"),
                        ],
                        help_text="The vocation name",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the vocation"
                    ),
                ),
                (
                    "strength_mod",
                    models.IntegerField(default=0, help_text="Strength modifier"),
                ),
                (
                    "agility_mod",
                    models.IntegerField(default=0, help_text="Agility modifier"),
                ),
                (
                    "endurance_mod",
                    models.IntegerField(default=0, help_text="Endurance modifier"),
                ),
                (
                    "reflexes_mod",
                    models.IntegerField(default=0, help_text="Reflexes modifier"),
                ),
                ("wit_mod", models.IntegerField(default=0, help_text="Wit modifier")),
                (
                    "intelligence_mod",
                    models.IntegerField(default=0, help_text="Intelligence modifier"),
                ),
                (
                    "willpower_mod",
                    models.IntegerField(default=0, help_text="Willpower modifier"),
                ),
                (
                    "perception_mod",
                    models.IntegerField(default=0, help_text="Perception modifier"),
                ),
                (
                    "charm_mod",
                    models.IntegerField(default=0, help_text="Charm modifier"),
                ),
                (
                    "appearance_mod",
                    models.IntegerField(default=0, help_text="Appearance modifier"),
                ),
                (
                    "graces_mod",
                    models.IntegerField(default=0, help_text="Graces modifier"),
                ),
                (
                    "cunning_mod",
                    models.IntegerField(default=0, help_text="Cunning modifier"),
                ),
                (
                    "has_alchemy",
                    models.BooleanField(default=False, help_text="Access to Alchemy"),
                ),
                (
                    "has_magery",
                    models.BooleanField(default=False, help_text="Access to Magery"),
                ),
                (
                    "has_sign_sorcery",
                    models.BooleanField(
                        default=False, help_text="Access to Sign Sorcery"
                    ),
                ),
                (
                    "has_crafting",
                    models.BooleanField(
                        default=False, help_text="Access to Crafting skills"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vocation",
                "verbose_name_plural": "Vocations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VocationFeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the feat", max_length=100),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of what the feat does"),
                ),
                (
                    "bonus_stat",
                    models.CharField(
                        blank=True,
                        help_text="Which stat this feat provides bonus dice for (e.g., 'strength', 'agility')",
                        max_length=50,
                    ),
                ),
                (
                    "bonus_dice",
                    models.IntegerField(
                        default=0, help_text="Number of bonus dice granted"
                    ),
                ),
                (
                    "trigger_condition",
                    models.CharField(
                        blank=True,
                        help_text="When this feat activates (e.g., 'defensive maneuvers', 'using swords')",
                        max_length=200,
                    ),
                ),
                (
                    "vocation",
                    models.ForeignKey(
                        help_text="The vocation this feat belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feats",
                        to="witcher_rpg.vocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vocation Feat",
                "verbose_name_plural": "Vocation Feats",
                "ordering": ["vocation", "name"],
            },
        ),
        migrations.CreateModel(
            name="WitcherCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(help_text="Character's IC name", max_length=100),
                ),
                (
                    "nation",
                    models.CharField(
                        blank=True, help_text="Nation or origin", max_length=100
                    ),
                ),
                (
                    "background",
                    models.TextField(
                        blank=True, help_text="Character background and history"
                    ),
                ),
                (
                    "experience_points",
                    models.IntegerField(
                        default=0, help_text="Total experience points earned"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "db_object",
                    models.OneToOneField(
                        help_text="The Evennia object this character data belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="witcher_character",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "skills",
                    models.OneToOneField(
                        help_text="Character's skill set",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character",
                        to="witcher_rpg.characterskills",
                    ),
                ),
                (
                    "stats",
                    models.OneToOneField(
                        help_text="Character's stat block",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character",
                        to="witcher_rpg.characterstats",
                    ),
                ),
                (
                    "vocation",
                    models.ForeignKey(
                        help_text="Character's vocation/class",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="characters",
                        to="witcher_rpg.vocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Witcher Character",
                "verbose_name_plural": "Witcher Characters",
                "ordering": ["-created_date"],
            },
        ),
    ]
