# Generated by Claude Code for Witcher RPG

from django.db import migrations


def populate_vocations(apps, schema_editor):
    """
    Populate the default vocations and their feats based on the Witcher universe.
    """
    Vocation = apps.get_model('witcher_rpg', 'Vocation')
    VocationFeat = apps.get_model('witcher_rpg', 'VocationFeat')

    # Knight
    knight = Vocation.objects.create(
        name='knight',
        description='Armored warriors sworn to a lord or code of honor. Masters of defense.',
        strength_mod=1,
        endurance_mod=1,
        willpower_mod=1,
        has_crafting=True
    )
    VocationFeat.objects.create(
        vocation=knight,
        name='Armored Combat',
        description='Extra dice when taking defensive maneuvers',
        bonus_stat='endurance',
        bonus_dice=2,
        trigger_condition='defensive maneuvers (rolling Endurance)'
    )

    # Bladesman
    bladesman = Vocation.objects.create(
        name='bladesman',
        description='Master swordsmen who have dedicated their lives to the blade.',
        agility_mod=2,
        reflexes_mod=1,
        has_crafting=False
    )
    VocationFeat.objects.create(
        vocation=bladesman,
        name='Master of the Sword',
        description='Extra dice to Agility when wielding swords',
        bonus_stat='agility',
        bonus_dice=2,
        trigger_condition='when using bladed weapons'
    )

    # Soldier
    soldier = Vocation.objects.create(
        name='soldier',
        description='Trained warriors and military personnel.',
        strength_mod=2,
        endurance_mod=1,
        has_crafting=False
    )
    VocationFeat.objects.create(
        vocation=soldier,
        name='Martial Training',
        description='Extra dice to Strength checks',
        bonus_stat='strength',
        bonus_dice=2,
        trigger_condition='physical combat and strength-based tasks'
    )

    # Witcher
    witcher = Vocation.objects.create(
        name='witcher',
        description='Mutated monster hunters with supernatural abilities.',
        reflexes_mod=1,
        agility_mod=1,
        endurance_mod=1,
        graces_mod=-2,
        appearance_mod=-1,
        has_alchemy=True,
        has_magery=False,
        has_sign_sorcery=True,
        has_crafting=True
    )
    VocationFeat.objects.create(
        vocation=witcher,
        name='Witcher Mutations',
        description='Enhanced physical capabilities from the Trial of the Grasses',
        bonus_stat='reflexes',
        bonus_dice=1,
        trigger_condition='all physical tasks'
    )

    # Sorcerer/ess
    sorcerer = Vocation.objects.create(
        name='sorcerer',
        description='Wielders of arcane magic, learned in the magical arts.',
        intelligence_mod=2,
        graces_mod=1,
        willpower_mod=1,
        has_alchemy=True,
        has_magery=True,
        has_crafting=True
    )
    VocationFeat.objects.create(
        vocation=sorcerer,
        name='Arcane Mastery',
        description='Natural affinity for magic',
        bonus_stat='intelligence',
        bonus_dice=2,
        trigger_condition='casting spells and magical research'
    )

    # Inquisitor
    inquisitor = Vocation.objects.create(
        name='inquisitor',
        description='Religious enforcers who hunt heretics and monsters.',
        willpower_mod=2,
        perception_mod=1,
        cunning_mod=1,
        has_alchemy=False,
        has_crafting=True
    )
    VocationFeat.objects.create(
        vocation=inquisitor,
        name='Zealous Conviction',
        description='Unwavering faith strengthens resolve',
        bonus_stat='willpower',
        bonus_dice=2,
        trigger_condition='resisting mental effects and intimidation'
    )

    # Courtesan
    courtesan = Vocation.objects.create(
        name='courtesan',
        description='Masters of social manipulation and information gathering.',
        charm_mod=2,
        appearance_mod=1,
        cunning_mod=1,
        graces_mod=1,
        has_alchemy=False
    )
    VocationFeat.objects.create(
        vocation=courtesan,
        name='Silver Tongue',
        description='Expert at persuasion and manipulation',
        bonus_stat='charm',
        bonus_dice=2,
        trigger_condition='social interactions and persuasion'
    )

    # Infiltrator
    infiltrator = Vocation.objects.create(
        name='infiltrator',
        description='Spies, thieves, and assassins who work in the shadows.',
        agility_mod=1,
        reflexes_mod=1,
        cunning_mod=2,
        perception_mod=1,
        has_alchemy=True
    )
    VocationFeat.objects.create(
        vocation=infiltrator,
        name='Shadow Walker',
        description='Expert at stealth and staying hidden',
        bonus_stat='cunning',
        bonus_dice=2,
        trigger_condition='stealth and infiltration'
    )

    # Noble
    noble = Vocation.objects.create(
        name='noble',
        description='Highborn individuals trained in leadership and courtly arts.',
        graces_mod=2,
        charm_mod=1,
        intelligence_mod=1,
        has_crafting=False
    )
    VocationFeat.objects.create(
        vocation=noble,
        name='Noble Bearing',
        description='Natural authority and social grace',
        bonus_stat='graces',
        bonus_dice=2,
        trigger_condition='leadership and formal social situations'
    )

    # Alchemist
    alchemist = Vocation.objects.create(
        name='alchemist',
        description='Master of potions, elixirs, and chemical compounds.',
        intelligence_mod=2,
        wit_mod=1,
        perception_mod=1,
        has_alchemy=True,
        has_crafting=True
    )
    VocationFeat.objects.create(
        vocation=alchemist,
        name='Chemical Expertise',
        description='Deep knowledge of alchemical processes',
        bonus_stat='intelligence',
        bonus_dice=2,
        trigger_condition='alchemy and potion-making'
    )

    # Merchant
    merchant = Vocation.objects.create(
        name='merchant',
        description='Traders and business-minded individuals skilled in negotiation.',
        cunning_mod=2,
        charm_mod=1,
        wit_mod=1,
        has_crafting=False
    )
    VocationFeat.objects.create(
        vocation=merchant,
        name='Deal Maker',
        description='Expert negotiator and appraiser',
        bonus_stat='cunning',
        bonus_dice=2,
        trigger_condition='trading, bartering, and negotiation'
    )


def reverse_populate_vocations(apps, schema_editor):
    """
    Remove all vocations and their feats.
    """
    Vocation = apps.get_model('witcher_rpg', 'Vocation')
    VocationFeat = apps.get_model('witcher_rpg', 'VocationFeat')

    VocationFeat.objects.all().delete()
    Vocation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('witcher_rpg', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_vocations, reverse_populate_vocations),
    ]
