# Generated by Django 5.2.8 on 2025-11-11 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("witcher_rpg", "0002_populate_vocations"),
    ]

    operations = [
        migrations.CreateModel(
            name="MagicElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("fire", "Fire"),
                            ("ice", "Ice"),
                            ("lightning", "Lightning"),
                            ("earth", "Earth"),
                            ("wind", "Wind"),
                            ("arcane", "Arcane"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Magic Element",
                "verbose_name_plural": "Magic Elements",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("elf", "Elf"),
                            ("dwarf", "Dwarf"),
                        ],
                        help_text="The race name",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the race"),
                ),
                (
                    "magic_cr_modifier",
                    models.IntegerField(
                        default=0,
                        help_text="Modifier to spell casting CR (negative is easier)",
                    ),
                ),
                (
                    "damage_taken_modifier",
                    models.FloatField(
                        default=1.0,
                        help_text="Multiplier for damage taken (1.0 is normal, >1.0 takes more damage)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Race",
                "verbose_name_plural": "Races",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WitcherStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("cat", "School of the Cat"),
                            ("viper", "School of the Viper"),
                            ("bear", "School of the Bear"),
                            ("eagle", "School of the Eagle"),
                            ("dragon", "School of the Dragon"),
                            ("basilisk", "School of the Basilisk"),
                        ],
                        help_text="The Witcher school/style name",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the fighting style"),
                ),
                ("agility_bonus", models.IntegerField(default=0)),
                ("reflexes_bonus", models.IntegerField(default=0)),
                ("strength_bonus", models.IntegerField(default=0)),
                ("endurance_bonus", models.IntegerField(default=0)),
                ("perception_bonus", models.IntegerField(default=0)),
                (
                    "special_ability",
                    models.TextField(
                        blank=True, help_text="Special ability granted by this style"
                    ),
                ),
            ],
            options={
                "verbose_name": "Witcher Style",
                "verbose_name_plural": "Witcher Styles",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="witchercharacter",
            name="race",
            field=models.CharField(
                choices=[("human", "Human"), ("elf", "Elf"), ("dwarf", "Dwarf")],
                default="human",
                help_text="Character's race",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="witchercharacter",
            name="witcher_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("cat", "School of the Cat"),
                    ("viper", "School of the Viper"),
                    ("bear", "School of the Bear"),
                    ("eagle", "School of the Eagle"),
                    ("dragon", "School of the Dragon"),
                    ("basilisk", "School of the Basilisk"),
                ],
                default="none",
                help_text="Witcher school style (only for Witcher vocation)",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CombatEncounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name/description of this combat encounter",
                        max_length=200,
                    ),
                ),
                (
                    "current_round",
                    models.IntegerField(default=1, help_text="Current combat round"),
                ),
                (
                    "current_turn_index",
                    models.IntegerField(
                        default=0, help_text="Index of the current participant's turn"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this combat is still ongoing"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        help_text="The room where combat is taking place",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combat_encounters",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combat Encounter",
                "verbose_name_plural": "Combat Encounters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CombatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initiative_roll",
                    models.IntegerField(
                        default=0,
                        help_text="Initiative roll (Reflexes + Perception + 1d10)",
                    ),
                ),
                (
                    "initiative_order",
                    models.IntegerField(
                        default=0, help_text="Turn order (lower goes first)"
                    ),
                ),
                (
                    "current_hp",
                    models.IntegerField(default=100, help_text="Current hit points"),
                ),
                (
                    "max_hp",
                    models.IntegerField(default=100, help_text="Maximum hit points"),
                ),
                (
                    "stance",
                    models.CharField(
                        choices=[
                            ("defensive", "Defensive"),
                            ("moderate", "Moderate"),
                            ("offensive", "Offensive"),
                        ],
                        default="moderate",
                        help_text="Current combat stance",
                        max_length=20,
                    ),
                ),
                (
                    "last_attack_type",
                    models.CharField(
                        choices=[
                            ("light", "Light Attack"),
                            ("standard", "Standard Attack"),
                            ("heavy", "Heavy Attack"),
                        ],
                        default="standard",
                        help_text="Last attack type used",
                        max_length=20,
                    ),
                ),
                (
                    "recovery_penalty",
                    models.IntegerField(
                        default=0,
                        help_text="Current penalty from recovery (frame disadvantage)",
                    ),
                ),
                (
                    "is_casting",
                    models.BooleanField(
                        default=False, help_text="Currently casting a spell"
                    ),
                ),
                (
                    "spell_turns_remaining",
                    models.IntegerField(
                        default=0, help_text="Turns remaining before spell is cast"
                    ),
                ),
                (
                    "spell_name",
                    models.CharField(
                        blank=True, help_text="Name of spell being cast", max_length=100
                    ),
                ),
                (
                    "spell_difficulty",
                    models.CharField(
                        blank=True,
                        help_text="Difficulty level of spell being cast",
                        max_length=20,
                    ),
                ),
                (
                    "spell_element",
                    models.CharField(
                        blank=True,
                        help_text="Element of spell being cast",
                        max_length=50,
                    ),
                ),
                (
                    "armor_value",
                    models.IntegerField(
                        default=0, help_text="Armor value for damage reduction"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this participant is still in combat (not dead/fled)",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The character participating in combat",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objects.objectdb",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="witcher_rpg.combatencounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combat Participant",
                "verbose_name_plural": "Combat Participants",
                "ordering": ["initiative_order"],
            },
        ),
    ]
