# Generated by Django 5.2.8 on 2025-11-11 13:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        (
            "witcher_rpg",
            "0003_magicelement_race_witcherstyle_witchercharacter_race_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BiomeMobTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "biome",
                    models.CharField(
                        choices=[
                            ("forest", "Forest"),
                            ("mine", "Mine"),
                            ("hills", "Hills"),
                            ("river", "River"),
                            ("ocean", "Ocean"),
                            ("plains", "Plains"),
                            ("mountains", "Mountains"),
                            ("swamp", "Swamp"),
                            ("desert", "Desert"),
                            ("urban", "Urban/City"),
                        ],
                        help_text="Biome this mob spawns in",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the mob type", max_length=100),
                ),
                ("description", models.TextField(help_text="Description of the mob")),
                (
                    "base_hp",
                    models.IntegerField(
                        default=50, help_text="Base HP for this mob type"
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        default=dict,
                        help_text="JSON dict of stats: {'strength': 5, 'agility': 4, ...}",
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        default=dict,
                        help_text="JSON dict of skills: {'blades': 3, 'athletics': 2, ...}",
                    ),
                ),
                ("gold_drop_min", models.IntegerField(default=0)),
                ("gold_drop_max", models.IntegerField(default=10)),
                (
                    "loot_table",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON list of possible loot drops",
                    ),
                ),
                (
                    "spawn_weight",
                    models.IntegerField(
                        default=10,
                        help_text="Weight for random spawning (higher = more common)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biome Mob Template",
                "verbose_name_plural": "Biome Mob Templates",
                "ordering": ["biome", "name"],
            },
        ),
        migrations.CreateModel(
            name="ItemTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(help_text="Description of the item")),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("tier_1", "Tier I - Common"),
                            ("tier_2", "Tier II - Good Crafting"),
                            ("tier_3", "Tier III - Exceptional"),
                            ("tier_4", "Tier IV - Relic/Artifact"),
                        ],
                        default="tier_1",
                        help_text="Item tier/rarity",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("weapon", "Weapon"),
                            ("armor", "Armor"),
                            ("consumable", "Consumable"),
                            ("material", "Crafting Material"),
                            ("quest", "Quest Item"),
                            ("misc", "Miscellaneous"),
                        ],
                        default="misc",
                        help_text="Item category",
                        max_length=20,
                    ),
                ),
                (
                    "gold_value",
                    models.IntegerField(default=0, help_text="Base gold value"),
                ),
                ("weight", models.FloatField(default=1.0, help_text="Weight in units")),
                (
                    "is_stackable",
                    models.BooleanField(
                        default=False, help_text="Can this item stack in inventory?"
                    ),
                ),
                (
                    "max_stack",
                    models.IntegerField(default=1, help_text="Maximum stack size"),
                ),
                (
                    "damage_bonus",
                    models.IntegerField(default=0, help_text="Damage bonus if weapon"),
                ),
                (
                    "armor_value",
                    models.IntegerField(default=0, help_text="Armor value if armor"),
                ),
                (
                    "stat_bonuses",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON dict of stat bonuses: {'strength': 2, 'agility': 1}",
                    ),
                ),
                (
                    "special_ability",
                    models.TextField(
                        blank=True,
                        help_text="Special ability description for relics/artifacts",
                    ),
                ),
                (
                    "required_materials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON dict of materials needed: {'iron_ore': 5, 'leather': 2}",
                    ),
                ),
                (
                    "crafting_skill_required",
                    models.CharField(
                        blank=True,
                        help_text="Crafting skill required (smithing, carpentry, herbalism)",
                        max_length=50,
                    ),
                ),
                (
                    "crafting_difficulty",
                    models.IntegerField(default=10, help_text="CR to craft this item"),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Item Template",
                "verbose_name_plural": "Item Templates",
                "ordering": ["tier", "category", "name"],
            },
        ),
        migrations.CreateModel(
            name="BankStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_stored",
                    models.IntegerField(
                        default=0,
                        help_text="Gold stored in bank",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_storage_slots",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum number of item stacks that can be stored",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.OneToOneField(
                        help_text="Character or organization that owns this storage",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_storage",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Storage",
                "verbose_name_plural": "Bank Storages",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold",
                    models.IntegerField(
                        default=0,
                        help_text="Gold owned",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        help_text="Character who owns this currency",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        help_text="Quantity if stackable",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(
                        blank=True,
                        help_text="Custom name for this specific item",
                        max_length=100,
                    ),
                ),
                (
                    "is_equipped",
                    models.BooleanField(
                        default=False, help_text="Is this item currently equipped?"
                    ),
                ),
                (
                    "condition",
                    models.IntegerField(
                        default=100,
                        help_text="Item condition (0-100%)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "custom_bonuses",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom stat bonuses for this specific item",
                    ),
                ),
                ("acquired_date", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Who owns this item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The template this item is based on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="witcher_rpg.itemtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "ordering": ["-is_equipped", "-template__tier", "template__name"],
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Mission name", max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Mission description and objectives"),
                ),
                (
                    "danger_level",
                    models.CharField(
                        choices=[
                            ("safe", "Safe"),
                            ("low", "Low Danger"),
                            ("moderate", "Moderate Danger"),
                            ("high", "High Danger"),
                            ("critical", "Critical Danger"),
                        ],
                        default="low",
                        help_text="Mission danger level",
                        max_length=20,
                    ),
                ),
                (
                    "is_plot_mission",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a storyteller-created plot mission?",
                    ),
                ),
                (
                    "base_gold_reward",
                    models.IntegerField(default=0, help_text="Base gold reward"),
                ),
                (
                    "experience_reward",
                    models.IntegerField(
                        default=0, help_text="Experience points awarded"
                    ),
                ),
                (
                    "loot_tier_weights",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON dict of tier weights: {'tier_1': 50, 'tier_2': 30, 'tier_3': 15, 'tier_4': 5}",
                    ),
                ),
                (
                    "artifact_multiplier",
                    models.FloatField(
                        default=1.0,
                        help_text="Multiplier for Tier IV (artifact) drops. Plot missions get 2.5x",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this mission currently active?"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="Has this mission been completed?"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "dungeon_master",
                    models.ForeignKey(
                        blank=True,
                        help_text="Player assigned as DM for this mission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dm_missions",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Characters participating in this mission",
                        related_name="participated_missions",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission",
                "verbose_name_plural": "Missions",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="MissionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        help_text="Type of action (joined, left, completed, failed, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of what happened"),
                ),
                (
                    "rewards_received",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON dict of rewards: {'gold': 100, 'xp': 50, 'items': [...]}",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        help_text="Character involved in this log",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_logs",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        help_text="Mission this log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="witcher_rpg.mission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission Log",
                "verbose_name_plural": "Mission Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WitcherRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("adventure", "Outdoor/Adventure Room"),
                            ("bank", "Bank/Storage Room"),
                            ("extraction", "Extraction/Resource Room"),
                        ],
                        default="adventure",
                        help_text="Type of room",
                        max_length=20,
                    ),
                ),
                (
                    "biome",
                    models.CharField(
                        choices=[
                            ("forest", "Forest"),
                            ("mine", "Mine"),
                            ("hills", "Hills"),
                            ("river", "River"),
                            ("ocean", "Ocean"),
                            ("plains", "Plains"),
                            ("mountains", "Mountains"),
                            ("swamp", "Swamp"),
                            ("desert", "Desert"),
                            ("urban", "Urban/City"),
                        ],
                        default="plains",
                        help_text="Biome type (for extraction and adventure rooms)",
                        max_length=20,
                    ),
                ),
                (
                    "danger_level",
                    models.CharField(
                        choices=[
                            ("safe", "Safe"),
                            ("low", "Low Danger"),
                            ("moderate", "Moderate Danger"),
                            ("high", "High Danger"),
                            ("critical", "Critical Danger"),
                        ],
                        default="safe",
                        help_text="Current danger level",
                        max_length=20,
                    ),
                ),
                (
                    "extraction_timer",
                    models.IntegerField(
                        default=0,
                        help_text="Timer for extraction rooms (0-100). At 100, becomes plot room.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "available_resources",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON dict of available resources: {'wood': 50, 'iron_ore': 30}",
                    ),
                ),
                (
                    "is_mission_active",
                    models.BooleanField(
                        default=False,
                        help_text="Is there an active mission in this room?",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization that owns this room (for bank/storage)",
                        max_length=100,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "room_object",
                    models.OneToOneField(
                        help_text="The Evennia room object",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="witcher_room",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Witcher Room",
                "verbose_name_plural": "Witcher Rooms",
            },
        ),
        migrations.AddField(
            model_name="mission",
            name="room",
            field=models.ForeignKey(
                help_text="Room where mission takes place",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="witcher_rpg.witcherroom",
            ),
        ),
        migrations.CreateModel(
            name="ExtractionResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "biome",
                    models.CharField(
                        choices=[
                            ("forest", "Forest"),
                            ("mine", "Mine"),
                            ("hills", "Hills"),
                            ("river", "River"),
                            ("ocean", "Ocean"),
                            ("plains", "Plains"),
                            ("mountains", "Mountains"),
                            ("swamp", "Swamp"),
                            ("desert", "Desert"),
                            ("urban", "Urban/City"),
                        ],
                        help_text="Biome this resource appears in",
                        max_length=20,
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(help_text="Name of the resource", max_length=100),
                ),
                (
                    "extraction_difficulty",
                    models.IntegerField(
                        default=10, help_text="CR to extract this resource"
                    ),
                ),
                (
                    "base_quantity_min",
                    models.IntegerField(
                        default=1, help_text="Minimum quantity extracted on success"
                    ),
                ),
                (
                    "base_quantity_max",
                    models.IntegerField(
                        default=5, help_text="Maximum quantity extracted on success"
                    ),
                ),
                (
                    "danger_increase_per_extraction",
                    models.IntegerField(
                        default=5,
                        help_text="How much the danger timer increases per extraction",
                    ),
                ),
                (
                    "item_template",
                    models.ForeignKey(
                        help_text="Item template for this resource",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_sources",
                        to="witcher_rpg.itemtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extraction Resource",
                "verbose_name_plural": "Extraction Resources",
                "ordering": ["biome", "resource_name"],
                "unique_together": {("biome", "resource_name")},
            },
        ),
    ]
