# Generated by Django 5.2.8 on 2025-11-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("witcher_rpg", "0012_advancement_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(
                help_text="Name of the shop (e.g., 'The Steel & Silver', 'Elegant Armaments')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="socialaction",
            name="bonus_effects",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional effects: {'penalty_cr': 5, 'bonus_dice': 2, 'duration': 3}",
            ),
        ),
        migrations.AlterField(
            model_name="socialencounter",
            name="name",
            field=models.CharField(
                help_text="Name/description of the social encounter (e.g., 'Seduction at the Ball')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="socialencounter",
            name="stakes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="What's at stake: {'gold': 1000, 'item': 'rare_perfume', 'favor': 'introduction_to_duke'}",
            ),
        ),
        migrations.AlterField(
            model_name="socialparticipant",
            name="max_social_capital",
            field=models.IntegerField(
                default=0,
                help_text="Maximum social capital (Charm + Cunning + Appearance + Graces) × multiplier",
            ),
        ),
    ]
