# Generated by Django 5.2.8 on 2025-11-11 16:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
        ("witcher_rpg", "0013_crafting_and_request_systems"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the set (e.g., 'Cat School Witcher Gear')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Lore and description of the set"),
                ),
                (
                    "set_type",
                    models.CharField(
                        choices=[
                            ("armor", "Armor Set"),
                            ("weapons", "Weapon Set"),
                            ("jewelry", "Jewelry Set"),
                            ("mixed", "Mixed Set"),
                        ],
                        default="armor",
                        help_text="Type of set",
                        max_length=50,
                    ),
                ),
                (
                    "tier",
                    models.IntegerField(
                        choices=[
                            (1, "Tier I"),
                            (2, "Tier II"),
                            (3, "Tier III"),
                            (4, "Tier IV"),
                        ],
                        default=3,
                        help_text="Set tier (usually III or IV)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "two_piece_bonus",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Bonus for wearing 2 pieces: {'stat': 'agility', 'value': 1}",
                    ),
                ),
                (
                    "three_piece_bonus",
                    models.JSONField(
                        blank=True, default=dict, help_text="Bonus for wearing 3 pieces"
                    ),
                ),
                (
                    "four_piece_bonus",
                    models.JSONField(
                        blank=True, default=dict, help_text="Bonus for wearing 4 pieces"
                    ),
                ),
                (
                    "five_piece_bonus",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Bonus for wearing 5+ pieces",
                    ),
                ),
            ],
            options={
                "ordering": ["tier", "name"],
            },
        ),
        migrations.CreateModel(
            name="CraftingRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the recipe (e.g., 'Moonblade Silver Sword Formula')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "crafting_type",
                    models.CharField(
                        choices=[
                            ("weaponsmithing", "Weaponsmithing"),
                            ("armorsmithing", "Armorsmithing"),
                            ("alchemy", "Alchemy"),
                            ("runecrafting", "Runecrafting"),
                            ("jewelcrafting", "Jewelcrafting"),
                            ("tailoring", "Tailoring"),
                        ],
                        help_text="Type of crafting required",
                        max_length=50,
                    ),
                ),
                (
                    "min_skill_level",
                    models.IntegerField(
                        default=5,
                        help_text="Minimum crafting skill level required",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "base_difficulty",
                    models.IntegerField(
                        default=50,
                        help_text="Base CR for crafting attempt (materials reduce this)",
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(150),
                        ],
                    ),
                ),
                (
                    "required_materials",
                    models.JSONField(
                        default=dict,
                        help_text="Materials needed: {'steel_ingot': 5, 'silver_dust': 2}",
                    ),
                ),
                (
                    "required_workshop",
                    models.CharField(
                        choices=[
                            ("forge", "Forge - Metalworking"),
                            ("laboratory", "Laboratory - Alchemy"),
                            ("enchanting_table", "Enchanting Table - Magic"),
                            ("workshop", "Workshop - General crafting"),
                            ("tailor_station", "Tailor Station - Clothing"),
                        ],
                        help_text="Workshop type required",
                        max_length=50,
                    ),
                ),
                (
                    "time_required_minutes",
                    models.IntegerField(
                        default=60,
                        help_text="Real-world minutes required to craft (or in-game time)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "xp_reward",
                    models.IntegerField(
                        default=50,
                        help_text="XP gained on successful craft",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "gold_cost",
                    models.IntegerField(
                        default=0,
                        help_text="Gold cost to use the recipe (workshop fees, etc)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_rare",
                    models.BooleanField(
                        default=False, help_text="Rare recipes are harder to find"
                    ),
                ),
                (
                    "discovery_location",
                    models.TextField(
                        blank=True,
                        help_text="Lore about where this recipe can be found",
                    ),
                ),
                (
                    "result_item",
                    models.ForeignKey(
                        help_text="Item produced by this recipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crafting_recipes",
                        to="witcher_rpg.itemtemplate",
                    ),
                ),
                (
                    "set_piece",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this item is part of a set",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipes",
                        to="witcher_rpg.itemset",
                    ),
                ),
            ],
            options={
                "ordering": ["crafting_type", "min_skill_level", "name"],
            },
        ),
        migrations.CreateModel(
            name="CraftingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(help_text="Whether the crafting succeeded"),
                ),
                ("roll_result", models.IntegerField(help_text="Dice roll result")),
                (
                    "difficulty",
                    models.IntegerField(help_text="CR that was rolled against"),
                ),
                (
                    "materials_used",
                    models.JSONField(
                        default=dict, help_text="Materials consumed in the attempt"
                    ),
                ),
                (
                    "xp_gained",
                    models.IntegerField(
                        default=0, help_text="XP gained (only on success)"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        help_text="Character who attempted crafting",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crafting_attempts",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        help_text="Recipe attempted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="witcher_rpg.craftingrecipe",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UnifiedRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("chargen", "Character Generation"),
                            ("advancement_stat", "Stat Advancement (6-7)"),
                            ("advancement_skill", "Skill Advancement (6-7)"),
                            ("special_item", "Special Item Request"),
                            ("plot_hook", "Plot Hook Request"),
                            ("custom", "Custom Request"),
                        ],
                        help_text="Type of request",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title of the request", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description and justification"
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured data for the request (character stats, advancement details, etc)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("revoked", "Revoked by Requester"),
                        ],
                        default="pending",
                        help_text="Current status",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        help_text="Priority level",
                        max_length=20,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="GM's notes on approval/denial"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requestor",
                    models.ForeignKey(
                        help_text="Player/character who submitted the request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_requests",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="GM who reviewed this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_unified_requests",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CharacterGenerationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        help_text="Proposed character name", max_length=200
                    ),
                ),
                ("race", models.CharField(help_text="Character race", max_length=50)),
                (
                    "social_rank",
                    models.IntegerField(
                        choices=[
                            (1, "Rank 1 - Outcast"),
                            (2, "Rank 2 - Commoner"),
                            (3, "Rank 3 - Knight/Small Gentry"),
                            (4, "Rank 4 - Landed Gentry"),
                            (5, "Rank 5 - Royalty"),
                        ],
                        default=2,
                        help_text="Social rank",
                    ),
                ),
                (
                    "stats_allocation",
                    models.JSONField(
                        help_text="Proposed stat allocation: {'strength': 3, 'agility': 4, ...}"
                    ),
                ),
                (
                    "skills_allocation",
                    models.JSONField(
                        help_text="Proposed skill allocation: {'blades': 4, 'alchemy': 2, ...}"
                    ),
                ),
                (
                    "background",
                    models.TextField(help_text="Character background and concept"),
                ),
                (
                    "stats_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether stat allocation is mechanically valid",
                    ),
                ),
                (
                    "skills_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether skill allocation is mechanically valid",
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of validation errors if any",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Country of origin",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="witcher_rpg.country",
                    ),
                ),
                (
                    "vocation",
                    models.ForeignKey(
                        help_text="Chosen vocation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="witcher_rpg.vocation",
                    ),
                ),
                (
                    "unified_request",
                    models.OneToOneField(
                        help_text="Link to unified request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chargen_details",
                        to="witcher_rpg.unifiedrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-unified_request__created_at"],
            },
        ),
        migrations.CreateModel(
            name="VocationSkillCostMultiplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(help_text="Name of the skill", max_length=50),
                ),
                (
                    "multiplier",
                    models.FloatField(
                        default=1.0,
                        help_text="XP cost multiplier (0.5 = half cost, 2.0 = double cost)",
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "vocation",
                    models.ForeignKey(
                        help_text="Vocation these multipliers apply to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_multipliers",
                        to="witcher_rpg.vocation",
                    ),
                ),
            ],
            options={
                "ordering": ["vocation", "skill_name"],
            },
        ),
        migrations.CreateModel(
            name="LearnedRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learned_date", models.DateTimeField(auto_now_add=True)),
                (
                    "times_crafted",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this character has crafted this recipe",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="Character who learned the recipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learned_recipes",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        help_text="Recipe learned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learned_by",
                        to="witcher_rpg.craftingrecipe",
                    ),
                ),
            ],
            options={
                "ordering": ["-learned_date"],
                "unique_together": {("character", "recipe")},
            },
        ),
        migrations.AddIndex(
            model_name="unifiedrequest",
            index=models.Index(
                fields=["status", "request_type"], name="witcher_rpg_status_f446c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedrequest",
            index=models.Index(
                fields=["requestor", "status"], name="witcher_rpg_request_543ed7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vocationskillcostmultiplier",
            unique_together={("vocation", "skill_name")},
        ),
    ]
